package id.ac.poliban.mi.maya.listpahlawan;

import java.util.ArrayList;
import java.util.List;

public class DataPahlawan {
    static List<Pahlawan> getAllPahlawan(){
        List<Pahlawan> data = new ArrayList<>();
        {
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Presiden_Sukarno.jpg/220px-Presiden_Sukarno.jpg","Ir. Soekarno","Dr.(H.C.) Ir. H. Soekarno1 (ER, EYD: Sukarno, nama lahir: Koesno Sosrodihardjo) (lahir di Surabaya, Jawa Timur, 6 Juni 1901 – meninggal di Jakarta, 21 Juni 1970 pada umur 69 tahun)[note 1][note 2] adalah Presiden pertama Republik Indonesia yang menjabat pada periode 1945–1967.[5]:11, 81 Ia memainkan peranan penting dalam memerdekakan bangsa Indonesia dari penjajahan Belanda.[6]:26-32 Ia adalah Proklamator Kemerdekaan Indonesia (bersama dengan Mohammad Hatta) yang terjadi pada tanggal 17 Agustus 1945. Soekarno adalah yang pertama kali mencetuskan konsep mengenai Pancasila sebagai dasar negara Indonesia dan ia sendiri yang menamainya.[6]"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/VP_Hatta.jpg/220px-VP_Hatta.jpg","Mohammad Hatta","Dr. (H.C.) Drs. H. Mohammad Hatta (populer sebagai Bung Hatta; lahir dengan nama Mohammad Athar di Fort de Kock, Hindia Belanda, 12 Agustus 1902 – meninggal di Jakarta, 14 Maret 1980 pada umur 77 tahun) adalah negarawan dan ekonom Indonesia yang menjabat sebagai Wakil Presiden Indonesia pertama. Ia bersama Soekarno memainkan peranan sentral dalam perjuangan kemerdekaan Indonesia dari penjajahan Belanda sekaligus memproklamirkannya pada 17 Agustus 1945. Ia pernah menjabat sebagai Perdana Menteri dalam Kabinet Hatta I, Hatta II, dan RIS. Pada 1956, ia mundur dari jabatan wakil presiden karena berselisih dengan Presiden Soekarno."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg/200px-COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg","R.A Kartini","Raden Adjeng Kartini (lahir di Jepara, Hindia Belanda, 21 April 1879 – meninggal di Rembang, Hindia Belanda, 17 September 1904 pada umur 25 tahun) atau sebenarnya lebih tepat disebut Raden Ayu Kartini[1] adalah seorang tokoh Jawa dan Pahlawan Nasional Indonesia. Kartini dikenal sebagai pelopor kebangkitan perempuan pribumi.Raden Adjeng Kartini berasal dari kalangan priyayi atau kelas bangsawan Jawa.[2] Ia merupakan putri dari Raden Mas Adipati Ario Sosroningrat, seorang patih yang diangkat menjadi bupati Jepara segera setelah Kartini lahir.[2] Kartini adalah putri dari istri pertama, tetapi bukan istri utama.[2] Ibunya bernama M.A. Ngasirah, putri dari Nyai Haji Siti Aminah dan Kyai Haji Madirono, seorang guru agama di Telukawur, Jepara.[2] Dari sisi ayahnya, silsilah Kartini dapat dilacak hingga Hamengkubuwana VI. Garis keturunan Bupati Sosroningrat bahkan dapat ditilik kembali ke istana Kerajaan Majapahit.[2] Semenjak Pangeran Dangirin menjadi bupati Surabaya pada abad ke-18, nenek moyang Sosroningrat mengisi banyak posisi penting di Pangreh Praja.[2]"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Tjoet_Nya%27_Dhien.jpg/220px-Tjoet_Nya%27_Dhien.jpg","Cut Nyak Dhien","Cut Nyak Dhien (ejaan lama: Tjoet Nja' Dhien, Lampadang, Kerajaan Aceh, 1848 – Sumedang, Jawa Barat, 6 November 1908; dimakamkan di Gunung Puyuh, Sumedang) adalah seorang Pahlawan Nasional Indonesia dari Aceh yang berjuang melawan Belanda pada masa Perang Aceh. Setelah wilayah VI Mukim diserang, ia mengungsi, sementara suaminya Ibrahim Lamnga bertempur melawan Belanda. Tewasnya Ibrahim Lamnga di Gle Tarum pada tanggal 29 Juni 1878 kemudian menyeret Cut Nyak Dhien lebih jauh dalam perlawanannya terhadap Belanda."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/1/17/Pattimura_2.jpg","Kapten Pattimura","Pattimura (Thomas Matulessy) lahir di Haria, pulau Saparua, Maluku, 8 Juni 1783 – meninggal di Ambon, Maluku, 16 Desember 1817 pada umur 34 tahun), juga dikenal dengan nama Kapitan Pattimura adalah Pahlawan nasional Indonesia dari Maluku.Menurut buku biografi Pattimura versi pemerintah yang pertama kali terbit, M Sapija menulis, \"Bahwa pahlawan Pattimura tergolong turunan bangsawan dan berasal dari Nusa Ina (Seram)\". Ayahnya yang bernama Antoni Matulessy adalah anak dari Kasimiliali Pattimura Mattulessy. Yang terakhir ini adalah putra raja Sahulau. Sahulau merupakan nama orang di negeri yang terletak dalam sebuah teluk di Seram. Namanya kini diabadikan untuk Universitas Pattimura, Kodam XVI/Pattimura dan Bandar Udara Pattimura di Ambon."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg/220px-Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg","Ki Hadjar Dewantara","Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 – meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun;[1] selanjutnya disingkat sebagai \"Soewardi\" atau \"KHD\") adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Portret_van_Tuanku_Imam_Bonjol.jpg/220px-Portret_van_Tuanku_Imam_Bonjol.jpg","Tuanku Imam Bonjol","Tuanku Imam Bonjol (lahir di Bonjol, Pasaman, Sumatra Barat, Indonesia, 1772 - wafat dalam pengasingan dan dimakamkan di Lotta, Pineleng, Minahasa, 6 November 1864) adalah salah seorang ulama, pemimpin dan pejuang yang berperang melawan Belanda dalam peperangan yang dikenal dengan nama Perang Padri pada tahun 1803-1838.[1] Tuanku Imam Bonjol diangkat sebagai Pahlawan Nasional Indonesia berdasarkan SK Presiden RI Nomor 087/TK/Tahun 1973, tanggal 6 November 1973.[2]"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sudirman.jpg/220px-Sudirman.jpg","Jendral Soedirman","Jenderal Besar Raden Soedirman (EYD: Sudirman; lahir 24 Januari 1916 – meninggal 29 Januari 1950 pada umur 34 tahun[a]) adalah seorang perwira tinggi Indonesia pada masa Revolusi Nasional Indonesia. Sebagai panglima besar Tentara Nasional Indonesia pertama, ia adalah sosok yang dihormati di Indonesia. Terlahir dari pasangan rakyat biasa di Purbalingga, Hindia Belanda, Soedirman diadopsi oleh pamannya yang seorang priyayi. Setelah keluarganya pindah ke Cilacap pada tahun 1916, Soedirman tumbuh menjadi seorang siswa rajin; ia sangat aktif dalam kegiatan ekstrakurikuler, termasuk mengikuti program kepanduan yang dijalankan oleh organisasi Islam Muhammadiyah. Saat di sekolah menengah, Soedirman mulai menunjukkan kemampuannya dalam memimpin dan berorganisasi, dan dihormati oleh masyarakat karena ketaatannya pada Islam. Setelah berhenti kuliah keguruan, pada 1936 ia mulai bekerja sebagai seorang guru, dan kemudian menjadi kepala sekolah, di sekolah dasar Muhammadiyah; ia juga aktif dalam kegiatan Muhammadiyah lainnya dan menjadi pemimpin Kelompok Pemuda Muhammadiyah pada tahun 1937. Setelah Jepang menduduki Hindia Belanda pada 1942, Soedirman tetap mengajar. Pada tahun 1944, ia bergabung dengan tentara Pembela Tanah Air (PETA) yang disponsori Jepang, menjabat sebagai komandan batalion di Banyumas. Selama menjabat, Soedirman bersama rekannya sesama prajurit melakukan pemberontakan, namun kemudian diasingkan ke Bogor."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/thumb/f/ff/Gusti_ngurah_rai.jpg/220px-Gusti_ngurah_rai.jpg","I Gusti Ngurah Rai","Brigadir Jenderal TNI (Anumerta) I Gusti Ngurah Rai (lahir di Desa Carangsari, Petang, Kabupaten Badung, Bali, Hindia Belanda, 30 Januari 1917 – meninggal di Marga, Tabanan, Bali, Indonesia, 20 November 1946 pada umur 29 tahun) adalah seorang pahlawan Indonesia dari Kabupaten Badung, Bali. Ngurah Rai memiliki pasukan yang bernama pasukan \"Ciung Wanara\" yang melakukan pertempuran terakhir yang dikenal dengan nama Puputan Margarana. (Puputan, dalam bahasa bali, berarti \"habis-habisan\", sedangkan Margarana berarti \"Pertempuran di Marga\"; Marga adalah sebuah desa ibu kota kecamatan di pelosok Kabupaten Tabanan, Bali) Di tempat puputan tersebut lalu didirikan Taman Pujaan Bangsa Margarana."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/thumb/c/c8/Pangeran_Antasari_Museum_Lambung_Mangkurat.JPG/220px-Pangeran_Antasari_Museum_Lambung_Mangkurat.JPG","Pangeran Antasari","Pangeran Antasari (lahir di Kayu Tangi, Kesultanan Banjar, 1797[1][2] atau 1809[3][4][5][6] – meninggal di Bayan Begok, Hindia Belanda, 11 Oktober 1862 pada umur 53 tahun) adalah seorang Pahlawan Nasional Indonesia.Ia adalah Sultan Banjar.[7] Pada 14 Maret 1862, dia dinobatkan sebagai pimpinan pemerintahan tertinggi di Kesultanan Banjar (Sultan Banjar) dengan menyandang gelar Panembahan Amiruddin Khalifatul Mukminin dihadapan para kepala suku Dayak dan adipati (gubernur) penguasa wilayah Dusun Atas, Kapuas dan Kahayan yaitu Tumenggung Surapati/Tumenggung Yang Pati Jaya Raja."));
        }
        return data;
    }
}
